config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  
  # Root path
  root 'queue_items#index'

  # Redirect /queue_items to the root path
  #get '/queue_items', to: redirect('/')

  resources :queue_items, only: [:index, :new, :create, :edit, :update, :show, :destroy]
  resources :api_keys, only: [:new, :create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :queue_items, only: [:create]
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Make all users login or sign up before accessing any page.
  before_action :authenticate_user!, except: [:new, :create]
  def after_sign_in_path_for(resource)
    root_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

    def bootstrap_class_for(flash_type)
      case flash_type.to_sym
      when :notice then "success"  # Green success message
      when :alert then "warning"   # Yellow warning message
      when :error then "danger"    # Red error message
      else "info"                  # Blue info message
      end
    end

    def bootstrap_class_name_for(status)
      status_classes = {
        "pending" => "warning",
        "complete" => "success",
        "printing" => "info",
        "failed" => "danger"
      }
      status_classes[status] || "secondary"  # Default to bg-light if status is not found
    end
      
end

app/views/application/_navbar.html.erb
<% if user_signed_in? %>
    <div style="height: 50vh;"></div>
    <nav class="navbar bg-body-tertiary position-fixed bottom-0 w-100 d-flex justify-content-around align-content-center py-3">
        <a class="bg-primary" style="position:absolute;width:70px;height:70px;border-radius:50%;top: -45px;left: calc(-35px - -50%);display: flex;flex-direction: column;justify-content: center;align-items: center;font-size: 3rem;color: white;"  href="<%= new_queue_item_path %>" aria-label="Add Queue Item">
        <i class="bi bi-plus-lg"></i>
        </a>
        <i class="bi bi-ban" style="font-size:35px"></i>
        <i class="bi bi-ban" style="font-size:35px"></i>
        <i class="bi bi-ban" style="font-size:35px"></i>
        <div class="dropdown dropup">
        <i class="bi bi-person-fill-gear px-2 " style="font-size:35px" data-bs-toggle="dropdown" aria-expanded="false"></i>
        <ul class="dropdown-menu dropdown-menu-end">
            <li>
            <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete, class: "dropdown-item text-danger" %>
            </li>
        </ul>
        </div>
    </nav>
<% end %>